version: "3.9"

services:
  api-mis-registros:
    container_name: api-mis-registros
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - mis-registros-network

  db-mis-registros:
    container_name: db-mis-registros
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mis-registros-network

volumes:
  pgdata:

networks:
  mis-registros-network:
    driver: bridge
