services:
  api-mis-registros-dev:
    container_name: api-mis-registros-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - API_KEY=${API_KEY}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public
      - NODE_ENV=development
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    networks:
      - mis-registros-network
    depends_on:
      - db-mis-registros
    restart: unless-stopped

  db-mis-registros:
    container_name: db-mis-registros
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mis-registros-network

volumes:
  pgdata:

networks:
  mis-registros-network:
    driver: bridge
