import { Unit } from "../../enums";

const dataIngredients = [
  { name: "Aceite de Oliva", unit: Unit.LITER },
  { name: "Aceite Vegetal", unit: Unit.LITER },
  { name: "Aceitunas", unit: Unit.GRAM },
  { name: "Acelga", unit: Unit.KILOGRAM },
  { name: "Aderezo César", unit: Unit.GRAM },
  { name: "Agua", unit: Unit.MILLILITER },
  { name: "Aguacate", unit: Unit.UNIT },
  { name: "Ajo", unit: Unit.UNIT },
  { name: "Albahaca", unit: Unit.GRAM },
  { name: "Almejas", unit: Unit.UNIT },
  { name: "Almendras", unit: Unit.GRAM },
  { name: "Anchoas en Lata", unit: Unit.UNIT },
  { name: "Apio", unit: Unit.UNIT },
  { name: "Arroz", unit: Unit.KILOGRAM },
  { name: "Arvejas", unit: Unit.GRAM },
  { name: "Atún en Lata", unit: Unit.UNIT },
  { name: "Avena", unit: Unit.KILOGRAM },
  { name: "Azafrán", unit: Unit.UNIT },
  { name: "Azúcar Blanca", unit: Unit.KILOGRAM },
  { name: "Azúcar Morena", unit: Unit.KILOGRAM },
  { name: "Bacalao", unit: Unit.KILOGRAM },
  { name: "Berberechos", unit: Unit.UNIT },
  { name: "Berros", unit: Unit.GRAM },
  { name: "Cacao en Polvo", unit: Unit.GRAM },
  { name: "Calabacín", unit: Unit.UNIT },
  { name: "Calamar", unit: Unit.KILOGRAM },
  { name: "Caldo de Pescado", unit: Unit.UNIT },
  { name: "Canela Molida", unit: Unit.GRAM },
  { name: "Carne Molida", unit: Unit.GRAM },
  { name: "Carne Picada", unit: Unit.GRAM },
  { name: "Carne de Cerdo", unit: Unit.GRAM },
  { name: "Carne de Vacuno", unit: Unit.GRAM },
  { name: "Cebolla", unit: Unit.UNIT },
  { name: "Cebolla Morada", unit: Unit.UNIT },
  { name: "Cerdo", unit: Unit.KILOGRAM },
  { name: "Champiñones", unit: Unit.GRAM },
  { name: "Chirimoya", unit: Unit.UNIT },
  { name: "Choclo", unit: Unit.UNIT },
  { name: "Chorizo", unit: Unit.GRAM },
  { name: "Chorizo Español", unit: Unit.GRAM },
  { name: "Chocolate Negro", unit: Unit.GRAM },
  { name: "Cilantro", unit: Unit.GRAM },
  { name: "Ciruelas Pasas", unit: Unit.GRAM },
  { name: "Clara de Huevo", unit: Unit.UNIT },
  { name: "Coco Rallado", unit: Unit.GRAM },
  { name: "Coliflor", unit: Unit.UNIT },
  { name: "Comino Molido", unit: Unit.GRAM },
  { name: "Crema de Leche", unit: Unit.LITER },
  { name: "Cúrcuma", unit: Unit.GRAM },
  { name: "Durazno", unit: Unit.UNIT },
  { name: "Espinacas", unit: Unit.GRAM },
  { name: "Fideos N°5", unit: Unit.KILOGRAM },
  { name: "Fideos N°77", unit: Unit.KILOGRAM },
  { name: "Fideos N°87", unit: Unit.KILOGRAM },
  { name: "Fideos Caracoles", unit: Unit.KILOGRAM },
  { name: "Fideos Corbatas", unit: Unit.KILOGRAM },
  { name: "Fideos Corbatitas", unit: Unit.KILOGRAM },
  { name: "Fideos Espirales", unit: Unit.KILOGRAM },
  { name: "Fideos Mostaccioli", unit: Unit.KILOGRAM },
  { name: "Fideos Mascarroni", unit: Unit.KILOGRAM },
  { name: "Fideos Quífaros", unit: Unit.KILOGRAM },
  { name: "Fideos Rigatoni", unit: Unit.KILOGRAM },
  { name: "Frambuesas", unit: Unit.GRAM },
  { name: "Garbanzos", unit: Unit.GRAM },
  { name: "Gelatina en Polvo", unit: Unit.GRAM },
  { name: "Gotas de Amargo de Angostura", unit: Unit.UNIT },
  { name: "Harina de Maíz", unit: Unit.KILOGRAM },
  { name: "Harina de Trigo", unit: Unit.KILOGRAM },
  { name: "Hielo", unit: Unit.GRAM },
  { name: "Huevo", unit: Unit.UNIT },
  { name: "Huevo Duro", unit: Unit.UNIT },
  { name: "Jamón", unit: Unit.GRAM },
  { name: "Jarabe de Goma", unit: Unit.GRAM },
  { name: "Jengibre", unit: Unit.GRAM },
  { name: "Judías Verdes", unit: Unit.GRAM },
  { name: "Jugo de Limón", unit: Unit.MILLILITER },
  { name: "Jugo de Lima", unit: Unit.MILLILITER },
  { name: "Kiwi", unit: Unit.UNIT },
  { name: "Langostinos", unit: Unit.GRAM },
  { name: "Lechuga", unit: Unit.UNIT },
  { name: "Lechuga Romana", unit: Unit.UNIT },
  { name: "Lentejas", unit: Unit.GRAM },
  { name: "Limón", unit: Unit.UNIT },
  { name: "Maíz", unit: Unit.KILOGRAM },
  { name: "Maíz para Palomitas", unit: Unit.KILOGRAM },
  { name: "Manzana", unit: Unit.UNIT },
  { name: "Mantequilla", unit: Unit.GRAM },
  { name: "Masa de Empanadas", unit: Unit.UNIT },
  { name: "Mariscos Varios", unit: Unit.KILOGRAM },
  { name: "Melocotón", unit: Unit.UNIT },
  { name: "Melón", unit: Unit.UNIT },
  { name: "Miel", unit: Unit.LITER },
  { name: "Mozzarella", unit: Unit.GRAM },
  { name: "Naranja", unit: Unit.UNIT },
  { name: "Nuez Moscada Molida", unit: Unit.GRAM },
  { name: "Nueces", unit: Unit.GRAM },
  { name: "Ñame", unit: Unit.KILOGRAM },
  { name: "Orégano", unit: Unit.GRAM },
  { name: "Palta", unit: Unit.UNIT },
  { name: "Pan", unit: Unit.KILOGRAM },
  { name: "Pan Tostado", unit: Unit.KILOGRAM },
  { name: "Panecillos de Pizza", unit: Unit.KILOGRAM },
  { name: "Papas", unit: Unit.KILOGRAM },
  { name: "Pargo", unit: Unit.KILOGRAM },
  { name: "Pasta", unit: Unit.KILOGRAM },
  { name: "Pepinillos", unit: Unit.UNIT },
  { name: "Pepino", unit: Unit.UNIT },
  { name: "Pepperoni", unit: Unit.UNIT },
  { name: "Pera", unit: Unit.UNIT },
  { name: "Pescado", unit: Unit.KILOGRAM },
  { name: "Pimienta", unit: Unit.GRAM },
  { name: "Pimentón Rojo", unit: Unit.UNIT },
  { name: "Pimentón Verde", unit: Unit.UNIT },
  { name: "Piña", unit: Unit.UNIT },
  { name: "Pisco", unit: Unit.MILLILITER },
  { name: "Plátano", unit: Unit.UNIT },
  { name: "Pollo", unit: Unit.KILOGRAM },
  { name: "Pollo Asado", unit: Unit.KILOGRAM },
  { name: "Puerro", unit: Unit.UNIT },
  { name: "Queso", unit: Unit.GRAM },
  { name: "Queso Mozzarella", unit: Unit.GRAM },
  { name: "Queso Parmesano", unit: Unit.GRAM },
  { name: "Quinoa", unit: Unit.GRAM },
  { name: "Rábano", unit: Unit.UNIT },
  { name: "Rúcula", unit: Unit.GRAM },
  { name: "Sal", unit: Unit.GRAM },
  { name: "Salchichas", unit: Unit.UNIT },
  { name: "Salsa de Tomate", unit: Unit.GRAM },
  { name: "Salsa de Soja", unit: Unit.LITER },
  { name: "Sardinas en Lata", unit: Unit.UNIT },
  { name: "Semillas de Sésamo", unit: Unit.GRAM },
  { name: "Tequila Blanco", unit: Unit.MILLILITER },
  { name: "Triple Sec", unit: Unit.MILLILITER },
  { name: "Tomate", unit: Unit.UNIT },
  { name: "Tomate Cherry", unit: Unit.UNIT },
  { name: "Tostitos", unit: Unit.GRAM },
  { name: "Trigo", unit: Unit.KILOGRAM },
  { name: "Uvas", unit: Unit.UNIT },
  { name: "Vainilla", unit: Unit.GRAM },
  { name: "Vinagre", unit: Unit.MILLILITER },
  { name: "Vino Blanco", unit: Unit.LITER },
  { name: "Vino Tinto", unit: Unit.LITER },
  { name: "Yogurt Natural", unit: Unit.LITER },
  { name: "Zanahoria", unit: Unit.UNIT },
  { name: "Zapallo", unit: Unit.UNIT },
];

export default dataIngredients;
