import { UnitList } from "../../../enums";

const dataIngredients = [
  { name: "Aceite de Oliva", unit: UnitList.MILLILITER },
  { name: "Aceite Vegetal", unit: UnitList.MILLILITER },
  { name: "Aceitunas", unit: UnitList.GRAM },
  { name: "Acelga", unit: UnitList.KILOGRAM },
  { name: "Aderezo César", unit: UnitList.TABLESPOON },
  { name: "Agua", unit: UnitList.MILLILITER },
  { name: "Aguacate", unit: UnitList.UNIT },
  { name: "Ajo", unit: UnitList.UNIT },
  { name: "Albahaca", unit: UnitList.GRAM },
  { name: "Almejas", unit: UnitList.UNIT },
  { name: "Almendras", unit: UnitList.GRAM },
  { name: "Anchoas en Lata", unit: UnitList.UNIT },
  { name: "Apio", unit: UnitList.UNIT },
  { name: "Arroz", unit: UnitList.GRAM },
  { name: "Arvejas", unit: UnitList.GRAM },
  { name: "Atún en Lata", unit: UnitList.UNIT },
  { name: "Avena", unit: UnitList.KILOGRAM },
  { name: "Azafrán", unit: UnitList.UNIT },
  { name: "Azúcar Blanca", unit: UnitList.KILOGRAM },
  { name: "Azúcar Morena", unit: UnitList.KILOGRAM },
  { name: "Bacalao", unit: UnitList.KILOGRAM },
  { name: "Berberechos", unit: UnitList.UNIT },
  { name: "Berros", unit: UnitList.GRAM },
  { name: "Cacao en Polvo", unit: UnitList.TABLESPOON },
  { name: "Calabacín", unit: UnitList.UNIT },
  { name: "Calamar", unit: UnitList.KILOGRAM },
  { name: "Caldo de Pescado", unit: UnitList.CUP },
  { name: "Canela Molida", unit: UnitList.TEASPOON },
  { name: "Carne Molida", unit: UnitList.GRAM },
  { name: "Carne Picada", unit: UnitList.GRAM },
  { name: "Carne de Cerdo", unit: UnitList.GRAM },
  { name: "Carne de Vacuno", unit: UnitList.GRAM },
  { name: "Cebolla", unit: UnitList.UNIT },
  { name: "Cebolla Morada", unit: UnitList.UNIT },
  { name: "Cerdo", unit: UnitList.KILOGRAM },
  { name: "Champiñones", unit: UnitList.GRAM },
  { name: "Chirimoya", unit: UnitList.UNIT },
  { name: "Choclo", unit: UnitList.UNIT },
  { name: "Chorizo", unit: UnitList.GRAM },
  { name: "Chorizo Español", unit: UnitList.GRAM },
  { name: "Chocolate Negro", unit: UnitList.GRAM },
  { name: "Cilantro", unit: UnitList.TABLESPOON },
  { name: "Ciruelas Pasas", unit: UnitList.GRAM },
  { name: "Clara de Huevo", unit: UnitList.UNIT },
  { name: "Coco Rallado", unit: UnitList.TABLESPOON },
  { name: "Coliflor", unit: UnitList.UNIT },
  { name: "Comino Molido", unit: UnitList.TEASPOON },
  { name: "Crema de Leche", unit: UnitList.CUP },
  { name: "Cúrcuma", unit: UnitList.TEASPOON },
  { name: "Durazno", unit: UnitList.UNIT },
  { name: "Espinacas", unit: UnitList.GRAM },
  { name: "Fideos N°5", unit: UnitList.KILOGRAM },
  { name: "Fideos N°77", unit: UnitList.KILOGRAM },
  { name: "Fideos N°87", unit: UnitList.KILOGRAM },
  { name: "Fideos Caracoles", unit: UnitList.KILOGRAM },
  { name: "Fideos Corbatas", unit: UnitList.KILOGRAM },
  { name: "Fideos Corbatitas", unit: UnitList.KILOGRAM },
  { name: "Fideos Espirales", unit: UnitList.KILOGRAM },
  { name: "Fideos Mostaccioli", unit: UnitList.KILOGRAM },
  { name: "Fideos Mascarroni", unit: UnitList.KILOGRAM },
  { name: "Fideos Quífaros", unit: UnitList.KILOGRAM },
  { name: "Fideos Rigatoni", unit: UnitList.KILOGRAM },
  { name: "Frambuesas", unit: UnitList.GRAM },
  { name: "Garbanzos", unit: UnitList.GRAM },
  { name: "Gelatina en Polvo", unit: UnitList.GRAM },
  { name: "Gotas de Amargo de Angostura", unit: UnitList.UNIT },
  { name: "Harina de Maíz", unit: UnitList.GRAM },
  { name: "Harina de Trigo", unit: UnitList.GRAM },
  { name: "Hielo", unit: UnitList.CUP },
  { name: "Huevo", unit: UnitList.UNIT },
  { name: "Huevo Duro", unit: UnitList.UNIT },
  { name: "Jamón", unit: UnitList.GRAM },
  { name: "Jarabe de Goma", unit: UnitList.TABLESPOON },
  { name: "Jengibre", unit: UnitList.GRAM },
  { name: "Judías Verdes", unit: UnitList.GRAM },
  { name: "Jugo de Limón", unit: UnitList.TABLESPOON },
  { name: "Jugo de Lima", unit: UnitList.TABLESPOON },
  { name: "Kiwi", unit: UnitList.UNIT },
  { name: "Langostinos", unit: UnitList.GRAM },
  { name: "Lechuga", unit: UnitList.UNIT },
  { name: "Lechuga Romana", unit: UnitList.UNIT },
  { name: "Lentejas", unit: UnitList.GRAM },
  { name: "Limón", unit: UnitList.UNIT },
  { name: "Maíz", unit: UnitList.KILOGRAM },
  { name: "Maíz para Palomitas", unit: UnitList.KILOGRAM },
  { name: "Manzana", unit: UnitList.UNIT },
  { name: "Mantequilla", unit: UnitList.GRAM },
  { name: "Masa de Empanadas", unit: UnitList.UNIT },
  { name: "Mariscos Varios", unit: UnitList.KILOGRAM },
  { name: "Melocotón", unit: UnitList.UNIT },
  { name: "Melón", unit: UnitList.UNIT },
  { name: "Miel", unit: UnitList.TABLESPOON },
  { name: "Mozzarella", unit: UnitList.GRAM },
  { name: "Naranja", unit: UnitList.UNIT },
  { name: "Nuez Moscada Molida", unit: UnitList.PINCH },
  { name: "Nueces", unit: UnitList.CUP },
  { name: "Ñame", unit: UnitList.KILOGRAM },
  { name: "Orégano", unit: UnitList.TEASPOON },
  { name: "Palta", unit: UnitList.UNIT },
  { name: "Pan", unit: UnitList.UNIT },
  { name: "Pan Tostado", unit: UnitList.UNIT },
  { name: "Panecillos de Pizza", unit: UnitList.KILOGRAM },
  { name: "Papas", unit: UnitList.KILOGRAM },
  { name: "Pargo", unit: UnitList.KILOGRAM },
  { name: "Pasta", unit: UnitList.KILOGRAM },
  { name: "Pepinillos", unit: UnitList.UNIT },
  { name: "Pepino", unit: UnitList.UNIT },
  { name: "Pepperoni", unit: UnitList.UNIT },
  { name: "Pera", unit: UnitList.UNIT },
  { name: "Pescado", unit: UnitList.KILOGRAM },
  { name: "Pimienta", unit: UnitList.PINCH },
  { name: "Pimentón Rojo", unit: UnitList.UNIT },
  { name: "Pimentón Verde", unit: UnitList.UNIT },
  { name: "Piña", unit: UnitList.UNIT },
  { name: "Pisco", unit: UnitList.MILLILITER },
  { name: "Plátano", unit: UnitList.UNIT },
  { name: "Pollo", unit: UnitList.KILOGRAM },
  { name: "Pollo Asado", unit: UnitList.KILOGRAM },
  { name: "Puerro", unit: UnitList.UNIT },
  { name: "Queso", unit: UnitList.GRAM },
  { name: "Queso Mozzarella", unit: UnitList.GRAM },
  { name: "Queso Parmesano", unit: UnitList.GRAM },
  { name: "Quinoa", unit: UnitList.GRAM },
  { name: "Rábano", unit: UnitList.UNIT },
  { name: "Rúcula", unit: UnitList.GRAM },
  { name: "Sal", unit: UnitList.TEASPOON },
  { name: "Salchichas", unit: UnitList.UNIT },
  { name: "Salsa de Tomate", unit: UnitList.CUP },
  { name: "Salsa de Soja", unit: UnitList.TABLESPOON },
  { name: "Sardinas en Lata", unit: UnitList.UNIT },
  { name: "Semillas de Sésamo", unit: UnitList.TEASPOON },
  { name: "Tequila Blanco", unit: UnitList.MILLILITER },
  { name: "Triple Sec", unit: UnitList.MILLILITER },
  { name: "Tomate", unit: UnitList.UNIT },
  { name: "Tomate Cherry", unit: UnitList.UNIT },
  { name: "Tostitos", unit: UnitList.GRAM },
  { name: "Trigo", unit: UnitList.GRAM },
  { name: "Uvas", unit: UnitList.GRAM },
  { name: "Vainilla", unit: UnitList.TEASPOON },
  { name: "Vinagre", unit: UnitList.TABLESPOON },
  { name: "Vino Blanco", unit: UnitList.MILLILITER },
  { name: "Vino Tinto", unit: UnitList.MILLILITER },
  { name: "Yogurt Natural", unit: UnitList.GRAM },
  { name: "Zanahoria", unit: UnitList.UNIT },
  { name: "Zapallo", unit: UnitList.UNIT },
];

export default dataIngredients;
